[canonical-tests]

# Test case: no rows
"a94dc47e-9d5f-4041-8e15-adbd586f8f4d" = true

# Test case: no columns
"f90a0e15-3bf1-4a19-85a9-51743820698a" = true

# Test case: no rectangles
"ec504712-fd6e-4b3d-8e6c-4c5fb54e3f1f" = true

# Test case: one rectangle
"27a01809-7597-47d6-8d90-7333aab4f1bb" = true

# Test case: two rectangles without shared parts
"f5d86269-4456-4ae5-aeaa-b7d72a87350c" = true

# Test case: five rectangles with shared parts
"4c0bfbe9-3e90-4be6-9363-844a24c990a1" = true

# Test case: rectangle of height 1 is counted
"58412b93-c2c0-495d-9049-5db9ccdada16" = true

# Test case: rectangle of width 1 is counted
"453fd421-9013-40a9-b9d4-baa026d36a2e" = true

# Test case: 1x1 square is counted
"c5003a0c-d325-4dbc-8f67-b88bfc15feb0" = true

# Test case: only complete rectangles are counted
"9f249916-4174-4997-9851-dd7152628af5" = true

# Test case: rectangles can be of different sizes
"8cd87934-1d07-42d6-ba00-5a041e6ab8cf" = true

# Test case: corner is required for a rectangle to be complete
"430c0054-ffb3-4e2e-bcb9-c3eda610921f" = true

# Test case: large input with many rectangles
"06f8f360-2970-44c5-9792-dfe273fa04d7" = true
