[canonical-tests]

# Test case: empty plaintext results in an empty ciphertext
"f1f127da-9cf8-4455-907a-cf2fbd6d0a57" = true

# Test case: Lowercase
"be8fa478-157f-4e34-8e63-44807bdb7bac" = true

# Test case: Remove spaces
"037c4258-d6d5-422e-a061-c7c050919c03" = true

# Test case: Remove punctuation
"fce82fde-e868-4551-b175-22b29a47fee9" = true

# Test case: 9 character plaintext results in 3 chunks of 3 characters
"f4075a81-bce1-47c8-b69b-f7340080eed0" = true

# Test case: 8 character plaintext results in 3 chunks, the last one with a trailing space
"4076db21-eb7b-48aa-9072-27b9fb8f346f" = true

# Test case: 54 character plaintext results in 7 chunks, the last two with trailing spaces
"fb979927-0675-45b1-8e56-7128e35f7081" = true
