[canonical-tests]

# Test case: One file, one match, no flags
"6c476eba-8a5f-4012-b577-2467786024f4" = true

# Test case: One file, one match, print line numbers flag
"a80661be-0edc-42f1-8375-6452caca3fd8" = true

# Test case: One file, one match, case-insensitive flag
"8022a47d-a5e1-46df-8b89-2dd0a1160ce7" = true

# Test case: One file, one match, print file names flag
"9fc05ce3-b29e-453f-b629-bb340c9babfe" = true

# Test case: One file, one match, match entire lines flag
"dd5c8142-6834-406f-8b25-257a9ebab3cc" = true

# Test case: One file, one match, multiple flags
"45907a13-c581-41bc-8835-0feaa0a6230c" = true

# Test case: One file, several matches, no flags
"1b7760c0-cf59-4a73-a08a-736998c0ca75" = true

# Test case: One file, several matches, print line numbers flag
"1ccbfc65-ce00-4f14-93dd-32084d083e0b" = true

# Test case: One file, several matches, match entire lines flag
"f176fd85-9f2c-4f11-870f-6883cf31cea0" = true

# Test case: One file, several matches, case-insensitive flag
"5c25344d-62e5-4107-82b8-3aa723a072c5" = true

# Test case: One file, several matches, inverted flag
"2b50c4a4-81a8-4340-ab7f-3de08b22f109" = true

# Test case: One file, no matches, various flags
"01e9be3a-9f74-41ec-a3c7-c652fab94ad6" = true

# Test case: One file, one match, file flag takes precedence over line flag
"fc9fc8e1-32da-4482-8d9c-d1a190acf102" = true

# Test case: One file, several matches, inverted and match entire lines flags
"3b273e4c-c18e-4144-ba5d-cb385c0bf9d6" = true

# Test case: Multiple files, one match, no flags
"bbe9a3c7-552f-47a5-aaa8-08c0663a7774" = true

# Test case: Multiple files, several matches, no flags
"e4d58a5f-9c29-474d-bc8f-53eb316fb7e6" = true

# Test case: Multiple files, several matches, print line numbers flag
"9516105e-1b22-4d5b-a454-d1ba8c723184" = true

# Test case: Multiple files, one match, print file names flag
"0afee9d6-d457-431f-a713-e01bb2a6e2f6" = true

# Test case: Multiple files, several matches, case-insensitive flag
"6b80c0d6-26c9-4f4c-a61f-4d8224a07f37" = true

# Test case: Multiple files, several matches, inverted flag
"ef48f601-978b-445b-b44d-6ae65695d750" = true

# Test case: Multiple files, one match, match entire lines flag
"e94d82b5-4013-44eb-8769-4b4ee7cc9615" = true

# Test case: Multiple files, one match, multiple flags
"8fd29269-1400-45ea-9ec3-c1e9ef5e66e3" = true

# Test case: Multiple files, no matches, various flags
"2c9bacfb-ef31-4024-9665-3789fd01232a" = true

# Test case: Multiple files, several matches, file flag takes precedence over line number flag
"ec77f27b-6de9-4e2b-a576-e5262701a4e8" = true

# Test case: Multiple files, several matches, inverted and match entire lines flags
"2b12fbfc-c528-49dc-acb4-9e314678f162" = true
