[canonical-tests]

# Test case: Smallest perfect number is classified correctly
"b274a4f4-21ee-4fd8-9d49-a968643906c6" = true

# Test case: Medium perfect number is classified correctly
"a4670329-4cce-4356-be9f-f0085cba8b23" = true

# Test case: Large perfect number is classified correctly
"4f3b3fc4-a3ca-486d-a423-591dd27dfd74" = true

# Test case: Smallest abundant number is classified correctly
"ab58f00f-88ed-4ffd-a5c1-a51dfe1ecd55" = true

# Test case: Medium abundant number is classified correctly
"6e328b02-9b09-4e53-abee-b53bbdbbfe1e" = true

# Test case: Large abundant number is classified correctly
"361e0279-5787-4846-a2f2-5b7099ff1462" = true

# Test case: Smallest prime deficient number is classified correctly
"0597d454-1791-4331-8eec-7ce69f4c0b1f" = true

# Test case: Smallest non-prime deficient number is classified correctly
"206f2cf3-c3f9-4fe2-8b46-f904bb9d31e2" = true

# Test case: Medium deficient number is classified correctly
"1c6b8be2-1326-4a32-bc10-be6fdc5108d1" = true

# Test case: Large deficient number is classified correctly
"d2f3ab00-6d9d-4aac-b953-3906cbaa4f15" = true

# Test case: Edge case (no factors other than itself) is classified correctly
"20c41626-28ad-4ed1-af4e-d09d9da275ca" = true

# Test case: Zero is rejected (not a natural number)
"7e4ef81d-5925-4037-a4e9-0552db79c185" = true

# Test case: Negative integer is rejected (not a natural number)
"bb0f7254-caed-451d-8f56-bda1d2d87b52" = true
