[canonical-tests]

# Test case: valid isbn number
"f49e4cd5-1d2e-4026-b62e-df5b6ff7c17a" = true

# Test case: invalid isbn check digit
"b7d57964-3be6-4261-8446-9cda9bba0bed" = true

# Test case: valid isbn number with a check digit of 10
"0e07193f-8c5f-4928-b387-01c6ad58bff0" = true

# Test case: check digit is a character other than X
"4294b690-fb2f-4470-ae82-999ce9a72e7c" = true

# Test case: invalid character in isbn
"056b32d7-7449-4fe1-8d8e-983051634858" = true

# Test case: X is only valid as a check digit
"fb8e997e-cf72-44a6-b5db-a6ca8d21b71b" = true

# Test case: valid isbn without separating dashes
"ec984bf9-14ad-4722-aeed-3b86bfb47ef6" = true

# Test case: isbn without separating dashes and X as check digit
"a5de3ce0-ab67-49e5-8516-e593d3e1a302" = true

# Test case: isbn without check digit and dashes
"353fc8d8-3dea-44c4-99f5-6c9c7cf64153" = true

# Test case: too long isbn and no dashes
"9a6f6b23-9cf5-4f00-9dc6-aa77c9cbb2c6" = true

# Test case: too short isbn
"6466cc6b-c289-4d05-8576-4a5711d5c5bd" = true

# Test case: isbn without check digit
"c27b97ba-b45c-4028-a56d-a15774df5193" = true

# Test case: check digit of X should not be used for 0
"add87aaf-aeba-4f5f-9f23-6eb58eae6135" = true

# Test case: empty isbn
"1fdb2b9f-94df-49cd-b1d6-336ccb6c88bf" = true

# Test case: input is 9 characters
"ce0f9ec5-bd55-4976-ba3c-c7d094b8c8c4" = true

# Test case: invalid characters are not ignored
"b1056078-6f14-434e-9d19-af93b33e9dd3" = true

# Test case: input is too long but contains a valid isbn
"14833faa-c01a-4a6f-a088-984801422a45" = true
