[canonical-tests]

# Test case: word beginning with a
"9a52f5ff-cbe3-4079-b6d7-877044dac3b4" = true

# Test case: word beginning with e
"b7b88f4a-0f17-4c54-8ec8-dc7ebc34d202" = true

# Test case: word beginning with i
"2f95cce8-68e9-4b29-9405-1d244afb5466" = true

# Test case: word beginning with o
"4106dbfa-72f2-44f0-ae4a-1cf5beaed60d" = true

# Test case: word beginning with u
"bd01e493-d02f-45bf-b3f6-aa9072183eee" = true

# Test case: word beginning with a vowel and followed by a qu
"11b4d9d2-13d7-4b7a-97fe-471dc3d505a1" = true

# Test case: word beginning with p
"39961a6f-1214-4293-bdd4-dab9f5479095" = true

# Test case: word beginning with k
"14092a6b-a47e-4cd1-bf9d-b08647007f78" = true

# Test case: word beginning with x
"5e8caf48-7c27-4cb4-ae13-98e27d98e17f" = true

# Test case: word beginning with q without a following u
"984a4b82-7bf6-4264-a7c9-0054f7c807f1" = true

# Test case: word beginning with ch
"71600c14-bbcf-44aa-8a96-8027c11ce295" = true

# Test case: word beginning with qu
"90ff9996-7025-4f30-bd3b-7fbcf082ba64" = true

# Test case: word beginning with qu and a preceding consonant
"86dbe852-4b98-4924-992c-619889e2f884" = true

# Test case: word beginning with th
"d9eef04d-4f9c-4b5f-9212-c9cc7ee5c895" = true

# Test case: word beginning with thr
"ea15bdb9-203b-45bc-8c1d-6304b9bebe71" = true

# Test case: word beginning with sch
"6ed23761-77c8-4a54-929e-f1e692ad3738" = true

# Test case: word beginning with yt
"b156ab82-afcc-46ba-bd10-33a464e980b1" = true

# Test case: word beginning with xr
"7aed7dad-71cb-4238-b1ac-8ea3657dae09" = true

# Test case: y is treated like a consonant at the beginning of a word
"2facb8da-f163-4356-9cfe-e90dd170bf4e" = true

# Test case: y is treated like a vowel at the end of a consonant cluster
"3aa84dac-dfc8-4776-a4c3-f1cc937e72bc" = true

# Test case: y as second letter in two letter word
"c9831ccd-2564-42e5-ab1b-3fac83c04ad0" = true

# Test case: a whole phrase
"268ad284-388d-481d-94d0-2802901f2b72" = true
