[canonical-tests]

# Test case: verse one - the house that jack built
"d9cf8868-4110-4089-99a7-76fbe02c3c12" = true

# Test case: verse two - the malt that lay
"3baa90d5-8327-4ba1-826a-fd0984db77a2" = true

# Test case: verse three - the rat that ate
"2faa77fa-3d3b-4c3c-a1be-8ff640db179e" = true

# Test case: verse four - the cat that killed
"e4d92e16-7a59-4546-a18c-7ab36578e5b8" = true

# Test case: verse five - the dog that worried
"05335434-0acd-4d88-a94e-1d290445c866" = true

# Test case: verse six - the cow with the crumpled horn
"b058a449-4e00-4f0b-afdc-6d7fea838a21" = true

# Test case: verse seven - the maiden all forlorn
"0d9a2c06-eb8c-4d19-b121-b08796e5b3a9" = true

# Test case: verse eight - the man all tattered and torn
"7d5c27db-8d6d-4170-aab4-c508735f0f54" = true

# Test case: verse nine - the priest all shaven and shorn
"405313a6-7d8b-4b31-ad08-5893039c83e4" = true

# Test case: verse 10 - the rooster that crowed in the morn
"a28e611d-9d45-4e8d-98ab-9d537c82775b" = true

# Test case: verse 11 - the farmer sowing his corn
"4fa6f393-2170-4458-a1b7-6c595236dc52" = true

# Test case: verse 12 - the horse and the hound and the horn
"92d2809e-83a5-4661-a107-d51f307ab6f3" = true

# Test case: multiple verses
"cf3cf693-fd89-4234-82f9-8ac8a8fc8234" = true

# Test case: full rhyme
"089fd298-67b7-4ad9-b485-04d55bb12878" = true
