[canonical-tests]

# Test case: single digit strings can not be valid
"f2c6e036-9235-4de5-8675-ec6e9087afc1" = true

# Test case: a single zero is invalid
"e25c7351-f17a-40c2-82aa-921723a14389" = true

# Test case: a simple valid SIN that remains valid if reversed
"e57508ad-c8c6-4962-a3ea-bc9572baaeeb" = true

# Test case: a simple valid SIN that becomes invalid if reversed
"153819f3-e87f-4cf8-bd5b-5ff217660f0b" = true

# Test case: a valid Canadian SIN
"8369ca01-ec42-4dd7-bbe0-1aef29b23b81" = true

# Test case: invalid Canadian SIN
"e8b96a2b-da11-4522-b0d4-900edc51476f" = true

# Test case: invalid credit card
"5fb0e551-addd-44d7-b580-b3d38ff559d0" = true

# Test case: invalid long number with an even remainder
"67dde846-089d-4df4-9e0e-69a87dc3c75e" = true

# Test case: valid number with an even number of digits
"a60d433e-db0e-4870-990d-860c75b94b58" = true

# Test case: valid number with an odd number of spaces
"5e5e6ac2-e8ca-4ee9-b67c-bc7166a066f9" = true

# Test case: valid strings with a non-digit added at the end become invalid
"329d7c32-ef0e-4b44-9a1d-8a13a955c8c1" = true

# Test case: valid strings with punctuation included become invalid
"5efe2974-b8ef-4901-b756-5294f8d2df14" = true

# Test case: valid strings with symbols included become invalid
"5906da87-ec34-4686-b001-12cb0b10e9af" = true

# Test case: single zero with space is invalid
"f0d6dc94-c8dd-4079-8a82-5f4bbb49e8cc" = true

# Test case: more than a single zero is valid
"5a4d1c5e-398e-428c-8a55-2fc657151c5d" = true

# Test case: input digit 9 is correctly converted to output digit 9
"9a4aa08f-8609-40dc-9b09-0028d5381d19" = true

# Test case: using ascii value for non-doubled non-digit isn't allowed
"66e2ed15-90fb-4dcb-a37e-6bb8ff6d9637" = true

# Test case: using ascii value for doubled non-digit isn't allowed
"e767ba33-2736-4b65-8062-aea4153b22f8" = true
