[canonical-tests]

# Test case: ability modifier for score 3 is -4
"5d6de04e-8208-4997-a4bc-406b41baa14c" = true

# Test case: ability modifier for score 4 is -3
"d1031b33-4849-4853-bc78-793b88978a20" = true

# Test case: ability modifier for score 5 is -3
"b3cf41ef-f3fa-47b7-80f5-7d9e47b40adb" = true

# Test case: ability modifier for score 6 is -2
"7d62ae22-072e-4eb3-8755-09b2b049b679" = true

# Test case: ability modifier for score 7 is -2
"f61fb99d-9f37-4e90-8bf3-a697ae777e0f" = true

# Test case: ability modifier for score 8 is -1
"946018e8-7a95-4fd2-9598-82d16f05ad0a" = true

# Test case: ability modifier for score 9 is -1
"3ebea6db-04d7-4cfb-85ab-4813fab4d2d8" = true

# Test case: ability modifier for score 10 is 0
"264fa9c7-49e3-408f-acf7-a8b2b5881768" = true

# Test case: ability modifier for score 11 is 0
"52d36e6d-f9a2-4eab-937e-452306a01ea4" = true

# Test case: ability modifier for score 12 is +1
"9cd3f482-bed1-4090-abdd-55f784d92b9b" = true

# Test case: ability modifier for score 13 is +1
"ad90f125-e4ea-4e70-919c-2c6d29ee6223" = true

# Test case: ability modifier for score 14 is +2
"566ce56a-62df-4122-86a3-a7c00ad5c628" = true

# Test case: ability modifier for score 15 is +2
"1a9615ee-f9c4-4726-90cc-3b2d3220748f" = true

# Test case: ability modifier for score 16 is +3
"6de08a36-046c-4b42-ac89-4f5d2d0390f1" = true

# Test case: ability modifier for score 17 is +3
"7c491292-38a6-4098-8449-5d0b1b8d0a94" = true

# Test case: ability modifier for score 18 is +4
"0aba0c94-39dd-4780-91c1-9ca700452f24" = true

# Test case: random ability is within range
"ebe89b9e-a65d-451d-a834-40f85a72c0df" = true

# Test case: random character is valid
"b6eacdfe-b7e5-41ff-8d28-d4c2784778fd" = true

# Test case: each ability is only calculated once
"91a68924-aa84-423b-ba29-113454cc781e" = true
