[canonical-tests]

# Test case: not allergic to anything
"448f9adf-9374-431f-b1ba-8d75ee594a85" = true

# Test case: allergic only to eggs
"d82c49b8-6c79-41c2-8957-698d3443c924" = true

# Test case: allergic to eggs and something else
"7f7a30ef-10ec-49eb-8b44-d6ccbc9ec6ad" = true

# Test case: allergic to something, but not eggs
"f103191d-9009-44c7-b25b-bce4506fc7a0" = true

# Test case: allergic to everything
"ce51be19-7fcc-45f0-91b8-08055e49e904" = true

# Test case: not allergic to anything
"1ed79c56-b342-45e1-a3d9-62176211e4b9" = true

# Test case: allergic only to peanuts
"b634d5bf-8648-4d09-92fe-456ada5cdc7f" = true

# Test case: allergic to peanuts and something else
"00f15885-c060-4136-8e45-a60484766205" = true

# Test case: allergic to something, but not peanuts
"c2d6f7c5-8d24-4fed-a7ee-cd1042deec65" = true

# Test case: allergic to everything
"7ab93153-eda7-43aa-b248-055e3f6939e6" = true

# Test case: not allergic to anything
"9d077e5f-7c4f-4119-9200-34a5ee11a4de" = true

# Test case: allergic only to shellfish
"bc81a235-c6c6-4eb1-81c2-1a7e5ad8b2ac" = true

# Test case: allergic to shellfish and something else
"c99edc72-b821-4e1f-b8f5-96748b9a3ecc" = true

# Test case: allergic to something, but not shellfish
"784a9b91-3a8e-459f-97c1-3dcee57b0d05" = true

# Test case: allergic to everything
"c392aaac-cdb0-4b72-9b05-1d51517e8c8c" = true

# Test case: not allergic to anything
"7ee25a77-33db-4e73-806d-7e7ed9744a1f" = true

# Test case: allergic only to strawberries
"eb74c490-e518-4b9a-86b7-49fd92e87170" = true

# Test case: allergic to strawberries and something else
"91af65c9-480d-497e-900f-5c449e33ce4d" = true

# Test case: allergic to something, but not strawberries
"66c9108d-7013-4d8b-b671-23f9a0a9b9ed" = true

# Test case: allergic to everything
"2b824979-486e-4b90-98e4-78354ca2d658" = true

# Test case: not allergic to anything
"2993db40-4f9a-4c63-9fdb-fda8571f7698" = true

# Test case: allergic only to tomatoes
"48e26342-1c65-4dae-be21-96b20e640bfa" = true

# Test case: allergic to tomatoes and something else
"43e28fb5-8396-4a0c-ae78-609c77223abf" = true

# Test case: allergic to something, but not tomatoes
"8d873a0a-3024-4ddf-a010-300c1a2d6b90" = true

# Test case: allergic to everything
"08c06eaa-c21a-4022-970d-f1e2a74b69fa" = true

# Test case: not allergic to anything
"c184f278-27d0-46ad-8a97-6bef8fab31de" = true

# Test case: allergic only to chocolate
"900d8f04-cdd0-474a-abb4-80a9affd7816" = true

# Test case: allergic to chocolate and something else
"979ba3e9-5c45-4f33-8b67-6d0aab77b6f5" = true

# Test case: allergic to something, but not chocolate
"d3864db2-0a13-4dc3-bc59-156a7c615f6a" = true

# Test case: allergic to everything
"18b5bf0e-2ade-4006-bbe5-0103fbaac071" = true

# Test case: not allergic to anything
"a84105e4-411d-4622-b239-de30aa9931b6" = true

# Test case: allergic only to pollen
"58a84370-d1f6-481b-9d82-ba05702f33ef" = true

# Test case: allergic to pollen and something else
"b06c34c3-9d17-403c-bc54-475f689b31ab" = true

# Test case: allergic to something, but not pollen
"eca80d7a-58b3-49fe-9b58-248a13782a45" = true

# Test case: allergic to everything
"97d2de8b-dd35-4c7c-9b30-a1fff1eabfbf" = true

# Test case: not allergic to anything
"924171f1-8bd7-452e-9668-0348a275cda6" = true

# Test case: allergic only to cats
"d605e3bd-d368-42f7-acca-07e65eafa87c" = true

# Test case: allergic to cats and something else
"a78b226b-e368-4df9-9b7d-ae47818e837e" = true

# Test case: allergic to something, but not cats
"0b02742f-b3d1-41a0-96d0-0372fa3b9bc0" = true

# Test case: allergic to everything
"37ce2cc6-b5b2-45b0-8b64-6945bdef9def" = true

# Test case: no allergies
"0d51b6ff-d005-479b-8f2d-c8b274dda275" = true

# Test case: just eggs
"75aff070-fe0c-461b-b8bc-9615781ba7e0" = true

# Test case: just peanuts
"9305056f-47d4-4e34-af2d-e98cf3b5d66a" = true

# Test case: just strawberries
"9a318ba7-e65f-4b1f-98d5-4fd7456775ae" = true

# Test case: eggs and peanuts
"d6ea0967-eb23-4caa-a044-94d3eda733e5" = true

# Test case: more than eggs but not peanuts
"2946a53e-2404-4dca-ac44-fffc01cb4959" = true

# Test case: lots of stuff
"027e737f-a7aa-4bb2-94d3-ee026f9bfd7a" = true

# Test case: everything
"04726c52-f8f4-4e0f-975c-2865c6b4011d" = true

# Test case: no allergen score parts
"1ce70741-2cf7-457f-903b-d787ba011f7e" = true
