[canonical-tests]

# Test case: just the header if no input
"368a0f45-5511-4e38-a4ca-c8d8d569a182" = true

# Test case: a win is three points, a loss is zero points
"1342b69b-3bc1-455c-86fe-32abc8274191" = true

# Test case: a win can also be expressed as a loss
"5cf05228-7736-4d78-a9aa-7710f24960cc" = true

# Test case: a different team can win
"7748b302-cc6f-4220-b432-ec4828689738" = true

# Test case: a draw is one point each
"cb9efc39-15ec-4037-80f8-fff4400d7b68" = true

# Test case: There can be more than one match
"9afc8c0e-8e33-436f-89cd-151290ab9ab6" = true

# Test case: There can be more than one winner
"3353e277-c533-4abb-9b4e-703aef8bc944" = true

# Test case: There can be more than two teams
"3f8a882a-93b3-446b-92bb-34703d7a6263" = true

# Test case: typical input
"e5ce19ea-8975-408a-889d-f5dcca1cb477" = true

# Test case: incomplete competition (not all pairs have played)
"b3e42b10-5f8a-4845-bf96-20a1a25c0eaa" = true

# Test case: ties broken alphabetically
"80f82f6e-225e-408c-9b47-b5cf3f645ded" = true
